name: Stacker
version: ${project.version}
main: de.zoeyvid.stacker.main
description: A Plugin to Stack Player on the top of a other Player
authors: [DavidCraftDev, Zoey2936]
website: https://github.com/ZoeyVid/Stacker
api-version: '1.13'
folia-supported: true

commands:
  stacker:
    description: a command to manage the Stacker plugin

permissions:
  stacker.*:
    description: the stacker permission gives all sub permissions
    children:
      stacker.help: true
      stacker.use: true
      stacker.immune: true
  stacker.help:
    description: allows to use /stacker help
    default: true
  stacker.use:
    description: allows yourself to stack others which are not immune and allows yourself to allow others to stack others which are not immune
    default: op
    children:
      stacker.use.self: true
      stacker.use.other: true
  stacker.use.self:
    description: allows yourself to stack others which are not immune
    default: true
  stacker.use.other:
    description: allows yourself to allow others to stack others which are not immune
    default: op
  stacker.immune:
    description: allows to make yourself immune and allows yourself to make others immune
    default: op
    children:
      stacker.immune.self: true
      stacker.immune.other: true
  stacker.immune.self:
    description: allows to make yourself immune
    default: true
  stacker.immune.other:
    description: allows yourself to make others immune
    default: op
default-permission: op
