name: build
on:
  push:
    branches:
      - develop
  pull_request:
  workflow_dispatch:
permissions:
  contents: read
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: actions/setup-java@b6effb05e454b25005698d916606bdc6ffcbf961 # v5.7.0
        with:
          java-version: 8
          distribution: corretto
      - name: version
        run: sed -i "s|0.0.0|$(cat .version)-dev|g" pom.xml
      - name: maven
        run: mvn -B package
      - uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          path: target/Stacker.jar
          archive: false
          if-no-files-found: error
          retention-days: 3
