name: JSON check
on:
  push:
  pull_request:
  workflow_dispatch:
jobs:
  test-json:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - name: json-syntax-check
        uses: limitusus/json-syntax-check@6e25e4304c75d72195ad8c6fca739cb2e99c3fb1 # v2.0.3
        with:
          pattern: "\\.json"
