name: shellcheck
on:
  push:
    branches:
      - develop
  pull_request:
  workflow_dispatch:
jobs:
  shellcheck:
    runs-on: ubuntu-slim
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - uses: ludeeus/action-shellcheck@00b27aa7cb85167568cb48a3838b75f4265f2bca # master
        with:
          check_together: 'yes'
